# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'MaximoRESTClient' do
  use_frameworks!
  pod 'Curry', '~> 4.0.0'
  pod 'Quick', '1.2.0'
  pod 'Nimble', '7.0.3'
end
