# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'MaximoRESTSDK' do
  use_frameworks!

  target 'MaximoRESTSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
